colorscheme tokyonight

set number
set relativenumber
set expandtab
set tabstop=4
set shiftwidth=4

set timeout
set timeoutlen=500

let mapleader=' '
noremap <leader>e :Neotree toggle<CR>

noremap <C-V> <ESC>"+p
vnoremap <C-C> "+y
noremap <C-A> <ESC>ggvG$
