name: update-flake-lock
on:
  workflow_dispatch: # allows manual triggering
  schedule:
    - cron: '0 0 * * 0' # runs weekly on Sunday at 00:00
    
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: 🔍 Checkout repository
        uses: actions/checkout@v4
      - name: 🔡 Install Nix
        uses: cachix/install-nix-action@v31
      - name: 🩹 Update flake.lock
        run: nix flake update
      - name: 🚀 Push update
        run: |
          git config --local user.name '🤖 Aktualisiernix'
          git config --local user.email 'noreply@noreply.github.com'
          git add flake.lock
          git commit -m "🩹 Update flake.lock"
          git push https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main

